version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db_app
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: ylab_hw
    ports:
      - 8000:8000
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile-tests
    container_name: test_container
    depends_on:
      - db_test

  db_test:
    image: postgres:15.1-alpine
    container_name: db_test_app
    command: -p 5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db_test"

volumes:
  postgres_data:
